### ISSUE TITLE
Protobuf Info

### ISSUE THREAD

**Issue by FernandezR** [hurlenko/mloader#1]
Hello,

Could you share how you created the response protobuf file? I want to create a similar application for a different site but I don't have a lot experience scrapping sites. 

Also, how did you figure out the decryption method? 

Thanks

**Comment by hurlenko** [comment]
Hi,

Both the decryption algorithm and response protobuf format were recovered from the obfuscated javascript code on the website. Everything was done manually by analyzing the source code.

**Comment by FernandezR** [comment]
Thanks for help, I'll take a look at the javascript to try and get an idea of how to do it for another site.
