### ISSUE TITLE
Invalid urls

### ISSUE THREAD

**Issue by barajasr** [hurlenko/mloader#11]
Change in viz url format leads to error/failure. No longer using the */viewer/# format format chapters for example. Now uses */title-chapter-#/chapter/#?action=read format.

**Comment by hurlenko** [comment]
Hi @barajasr,

Can you give a sample url? I still get the same `viewer`/`title` url scheme and everything works for me.

**Comment by barajasr** [comment]
oh my bad. it seems some script I had in the background was picking up biz links. I apologise, should have noticed that beforehand. I'm sorry for the unnecessary ticket.
