### ISSUE TITLE
Append ‘chapter sub-title (escaped)’ to  chapter filename

### ISSUE THREAD

**Issue by ath-x01** [hurlenko/mloader#13]
Hello, just wondering was there a particular reason you wouldn't do this? I know the sub-title comes in various prefix like [Number #n:..., Chapter #n:..., #n:]. But its still possible to filter and omit all of those with regex and just grab the following sub-title, right?

Would be good as a reference for jumping between chapters.

**Comment by hurlenko** [comment]
Hi @ath-x01,

File naming scheme was based on https://github.com/Daiz/manga-naming-scheme, see #6 for more details. This might seem inconvenient as chapter names don't include titles but this scheme seems to be an established convention so I don't think it should be changed.

**Comment by ath-x01** [comment]
Understandable, thought there were  more of a technical reason behind it. Pretty sure these chapters will still sorted out well as long as i keep the ordered marking intact. Just tryna make sure here before i make the changes myself. 

Anyway thank you so much for your tools, its really helpful 🙏🏻

**Comment by hurlenko** [comment]
You are welcome 🙂
If you find any more problems feel free to open another issue.

**Comment by ultimatespirit** [comment]
For what it's worth, chapter titles *technically* can be included under the `[Extra Information]` section of Daiz. It makes the file names fairly long and cumbersome, but I can see the appeal for some (I personally prefer eliding that info). You could perhaps include an optional switch for stuffing the chapter titles into that extra information section for that case and it would still be conforming to current standards, though not sure how many really care for that info in the file names.

**Comment by hurlenko** [comment]
Hi @ultimatespirit @howot,

It is now possible to add chapter titles to file names in the latest version of `mloader`.
