### ISSUE TITLE
cant download image for another language except english

### ISSUE THREAD

**Issue by syahqi8** [hurlenko/mloader#15]
![01](https://user-images.githubusercontent.com/88753943/128955181-3824daa9-c761-4722-8332-3c0c78ffcb5f.PNG)
what should i do ?? any recommendations ?? please help.

**Comment by hurlenko** [comment]
Hello @syahqi8 @attalix ,

Please try the latest version on mloader (`pip install -U mloader`). Should be fixed now

**Comment by attalix** [comment]
Thanks. Works.
