### ISSUE TITLE
Titles of extra chapters are added to the file name by default

### ISSUE THREAD

**Issue by TissuePowder** [hurlenko/mloader#18]
Works fine for normal chapters, but extra (ex) chapter titles are appended to the file name by default. This shouldn't be the expected behavior as `--chapter-title` option was not used.

Used command:
```
$ mloader https://mangaplus.shueisha.co.jp/titles/100041
```
Part of the filenames:
>Summer Time Rendering - c007 (web) [Viz].cbz
>Summer Time Rendering - c007x1 (web) [Record 001 Shiori Kobayakawa s Diary Excerpt] [Viz].cbz
>Summer Time Rendering - c011 (web) [Viz].cbz
>Summer Time Rendering - c011x1 (web) [Record 002 Reviews of Ryuunosuke Nagumo s Swampman] [Viz].cbz

**Comment by TissuePowder** [comment]
Another note, `#ex Record #18 Flowers That Bloom On Hitogashima` chapter should have been saved as `c101x1`, but instead it gets saved as `0ex`.

**Comment by hurlenko** [comment]
Hi, thanks for pointing that out. I was following [this naming scheme](https://github.com/Daiz/manga-naming-scheme) which says:

> x0 is intended to be used with chapters that deviate from a clear numbering system (eg. decimal chapter numbers like 10.5) already in place and must be used for these, and must be left out for regular chapters. [Extra Information] is **recommended** in these cases to specify the type of the chapter.

But as long as there's a switch to toggle this behavior, one would expect it to work consistently regardless of chapter type.

As for the naming bug - it is now fixed. Please update🙂
