### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by Tosh0kan** [hurlenko/mloader#28]
Title pretty much. Is the project dead?

**Comment by darodi** [comment]
it does not seem maintained but it's still working.
 
Here is a pull request with some improvements
- https://github.com/hurlenko/mloader/pull/26
- https://github.com/darodi/mloader


list of changes 
- skip already downloader chapter
- new option to save raw images in sub directory by chapter
- Remove Viz from filenames
