### ISSUE TITLE
PROBLEM

### ISSUE THREAD

**Issue by psanchez4** [hurlenko/mloader#3]
In some mangas, the quality of some images is too low compared with others of the same manga. Also  the program doesn´t download all the pages of the selected manga. For example, in:
https://manga plus shueisha co jp/viewer/2001777
The program only download 55 pages and it has 58

**Comment by hurlenko** [comment]
The counter on the website does not show the actual number of pages, it also includes pages with ads and links to the next chapters. I tried to download the chapter from the link that you gave and the program downloaded all the pages correctly(compared with other sources).

As for the image quality, the program does not do any image processing/conversion, it only downloads images from the website so you basically get the same quality as if you are reading online. However, I've just noticed that the default quality was not set to the maximum possible level. I made some changes, you can update by running `pip install -U mloader` and see if it helps.

**Comment by psanchez4** [comment]
I have try it and now works fantastic. Thanks for your work
