### ISSUE TITLE
License mismatch in setup.py

### ISSUE THREAD

**Issue by marsam** [hurlenko/mloader#30]
**Describe the bug**

The LICENSE file specifies GPL3, but the license listed in `setup.py` is MIT
https://github.com/hurlenko/mloader/blob/1a64c2e0a80f9377fb99bfa1b8e98312c8e15d9d/setup.py#L36

**Expected behavior**
Both licenses should match to help packaging mloader.

- PyPI shows [`MIT License (GPLv3)`](https://pypi.org/project/mloader/)
- aur uses [GPL 3](https://aur.archlinux.org/packages/mloader) 
- nixpkgs uses [GPL 3](https://github.com/NixOS/nixpkgs/blob/35a81f2925e4bfa5321b5777cff03fc56a7758aa/pkgs/tools/misc/mloader/default.nix#L29) (I'm maintainer) 

**Stack trace**

**Environment (please complete the following information):**
 - OS: MacOS
 - Python version: Python 10
 - mloader version: HEAD ([1a64c2e](https://github.com/hurlenko/mloader/commit/1a64c2e0a80f9377fb99bfa1b8e98312c8e15d9d))
 - Mangaplus URL:

**Comment by NovusEdge** [comment]
I think this would be a quick fix, do you mind if I take this issue up?

**Comment by hurlenko** [comment]
@marsam Thanks for reporting the issue!

@NovusEdge Yep, feel free, thanks!
