### ISSUE TITLE
PyPI tarball doesn't include requirements.txt

### ISSUE THREAD

**Issue by marsam** [hurlenko/mloader#31]
**Describe the bug**
The [PyPI tarball](https://pypi.org/project/mloader/ ) doesn't include the `requirements.txt` which is required by setup.py https://github.com/hurlenko/mloader/blob/1a64c2e0a80f9377fb99bfa1b8e98312c8e15d9d/setup.py#L19
Hence the installation fails when someone uses PyPI
```
$ pip install mloader
...
Traceback (most recent call last):
  File "/private/tmp/nix-build-mloader-1.1.8.drv-0/mloader-1.1.8/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 19, in <module>
    with open("requirements.txt", "r", "utf-8") as f:
  File "/nix/store/76b5vjb1wkl7b38g8pazwv0p6pxmi53f-python3-3.10.5/lib/python3.10/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Expected behavior**
Be able to install mloader from PyPI

**Stack trace**

**Environment (please complete the following information):**
 - OS: MacOS
 - Python version: Python 10
 - mloader version: HEAD ([1a64c2e](https://github.com/hurlenko/mloader/commit/1a64c2e0a80f9377fb99bfa1b8e98312c8e15d9d))
 - Mangaplus URL:

**Comment by hurlenko** [comment]
Fixed, thanks!
