### ISSUE TITLE
I'm having issue in downloading this new manga

### ISSUE THREAD

**Issue by BLSTR13** [hurlenko/mloader#40]
I don't know what's really the problem here but maybe because it's a new manga so it has had to with maybe the code or something idk, here is the link btw [The new manga about sasuke](https://mangaplus.shueisha.co.jp/titles/100212)

**Comment by darodi** [comment]
works fine

```
python -m mloader -r --chapter-subdir -t 100212

            _                 _
  _ __ ___ | | ___   __ _  __| | ___ _ __
 | '_ ` _ \| |/ _ \ / _` |/ _` |/ _ \ '__|
 | | | | | | | (_) | (_| | (_| |  __/ |
 |_| |_| |_|_|\___/ \__,_|\__,_|\___|_|

09.11.2022 20:30:41 |   INFO   |  __main__.py   206  | Started export
09.11.2022 20:30:42 |   INFO   |   loader.py    138  | 1/1) Manga: Naruto: Sasuke's Story—The Uchiha and the Heavenly Stardust: The Manga
09.11.2022 20:30:42 |   INFO   |   loader.py    139  |     Author: Masashi Kishimoto/Jun Esaka/Shingo Kimura
09.11.2022 20:30:42 |   INFO   |   loader.py    150  |     1/2) Chapter #002: Chapter 2
#002  [####################################]  43/43
09.11.2022 20:30:50 |   INFO   |   loader.py    150  |     2/2) Chapter #001: Chapter 1
#001  [####################################]  53/53
09.11.2022 20:30:58 |   INFO   |  __main__.py   224  | SUCCESS

```

**Comment by BLSTR13** [comment]
mloader -q super_high --chapter-title https://mangaplus.shueisha.co.jp/titles/100212

            _                 _
  _ __ ___ | | ___   __ _  __| | ___ _ __
 | '_ ` _ \| |/ _ \ / _` |/ _` |/ _ \ '__|
 | | | | | | | (_) | (_| | (_| |  __/ |
 |_| |_| |_|_|\___/ \__,_|\__,_|\___|_|

10.11.2022 03:36:01 |   INFO   |  __main__.py   206  | Started export
10.11.2022 03:36:02 |   INFO   |   loader.py    138  | 1/1) Manga: Naruto: Sasuke's Story—The Uchiha and the Heavenly Stardust: The Manga
10.11.2022 03:36:02 |   INFO   |   loader.py    139  |     Author: Masashi Kishimoto/Jun Esaka/Shingo Kimura
10.11.2022 03:36:02 |   INFO   |   loader.py    150  |     1/2) Chapter #002: Chapter 2
10.11.2022 03:36:02 |  ERROR   |  __main__.py   223  | Failed to download manga
Traceback (most recent call last):
  File "C:\Users\Cherri Estudillo\AppData\Roaming\Python\Python310\site-packages\mloader\__main__.py", line 215, in main
    loader.download(
  File "C:\Users\Cherri Estudillo\AppData\Roaming\Python\Python310\site-packages\mloader\loader.py", line 189, in download
    self._download(manga_list)
  File "C:\Users\Cherri Estudillo\AppData\Roaming\Python\Python310\site-packages\mloader\loader.py", line 154, in _download
    exporter = self.exporter(
  File "C:\Users\Cherri Estudillo\AppData\Roaming\Python\Python310\site-packages\mloader\exporter.py", line 136, in __init__
    self.archive = zipfile.ZipFile(
  File "C:\Program Files\Python310\lib\zipfile.py", line 1249, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'mloader_downloads\\Naruto Sasuke S Story The Uchiha And The Heavenly Stardust The Manga\\Naruto Sasuke S Story The Uchiha And The Heavenly Stardust The Manga - c002 (web) [Chapter 2] [Unknown].cbz'
10.11.2022 03:36:02 |   INFO   |  __main__.py   224  | SUCCESS


This is what it's showing me

**Comment by BLSTR13** [comment]
> 

I tried what you did but
```
mloader -r --chapter-subdir -t 100212

            _                 _
  _ __ ___ | | ___   __ _  __| | ___ _ __
 | '_ ` _ \| |/ _ \ / _` |/ _` |/ _ \ '__|
 | | | | | | | (_) | (_| | (_| |  __/ |
 |_| |_| |_|_|\___/ \__,_|\__,_|\___|_|

10.11.2022 03:37:37 |   INFO   |  __main__.py   206  | Started export
10.11.2022 03:37:37 |   INFO   |   loader.py    138  | 1/1) Manga: Naruto: Sasuke's Story—The Uchiha and the Heavenly Stardust: The Manga
10.11.2022 03:37:37 |   INFO   |   loader.py    139  |     Author: Masashi Kishimoto/Jun Esaka/Shingo Kimura
10.11.2022 03:37:38 |   INFO   |   loader.py    150  |     1/2) Chapter #002: Chapter 2
10.11.2022 03:37:38 |  ERROR   |  __main__.py   223  | Failed to download manga
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 206] The filename or extension is too long: 'mloader_downloads\\Naruto Sasuke S Story The Uchiha And The Heavenly Stardust The Manga\\Naruto Sasuke S Story The Uchiha And The Heavenly Stardust The Manga - c002 (web) [Unknown]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cherri Estudillo\AppData\Roaming\Python\Python310\site-packages\mloader\__main__.py", line 215, in main
    loader.download(
  File "C:\Users\Cherri Estudillo\AppData\Roaming\Python\Python310\site-packages\mloader\loader.py", line 189, in download
    self._download(manga_list)
  File "C:\Users\Cherri Estudillo\AppData\Roaming\Python\Python310\site-packages\mloader\loader.py", line 154, in _download
    exporter = self.exporter(
  File "C:\Users\Cherri Estudillo\AppData\Roaming\Python\Python310\site-packages\mloader\exporter.py", line 117, in __init__
    self.path.mkdir(parents=True, exist_ok=True)
  File "C:\Program Files\Python310\lib\pathlib.py", line 1180, in mkdir
    self.mkdir(mode, parents=False, exist_ok=exist_ok)
  File "C:\Program Files\Python310\lib\pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 206] The filename or extension is too long: 'mloader_downloads\\Naruto Sasuke S Story The Uchiha And The Heavenly Stardust The Manga\\Naruto Sasuke S Story The Uchiha And The Heavenly Stardust The Manga - c002 (web) [Unknown]'
10.11.2022 03:37:38 |   INFO   |  __main__.py   224  | SUCCESS

**Comment by BLSTR13** [comment]
The filename or extension is too long: 'mloader_downloads\\Naruto Sasuke S Story The Uchiha And The Heavenly Stardust The Manga\\Naruto Sasuke S Story The Uchiha And The Heavenly Stardust The Manga - c002 (web) [Unknown]'

it says this

**Comment by darodi** [comment]
The directory path for mloader_downloads may be too long.
You could try to move it in a shorter path name.
