### ISSUE TITLE
Any chance for K Manga support?

### ISSUE THREAD

**Issue by Fourpokechat** [hurlenko/mloader#45]
Or maybe a new repository all together? Maybe call it kmloader?

**Comment by darodi** [comment]
> This service is not available in your region. We greatly appreciate your understanding.

Where is it available?

**Comment by Fourpokechat** [comment]
> > This service is not available in your region. We greatly appreciate your understanding.
> 
> Where is it available?

Only in th U.S. right now, just launched a few days ago.

**Comment by Fourpokechat** [comment]
> > This service is not available in your region. We greatly appreciate your understanding.
> 
> Where is it available?
> 
> *** edit *** OK, USA only :(

Does it being region lock make it nearly impossible to do?

**Comment by hurlenko** [comment]
Hey @Fourpokechat, this project was created for one specific manga source and was not meant to be extended with alternative manga sources in the first place. I'm having hard time maintaining this project, let alone implementing another one from scratch. So for the time being this is a no from me, sorry.
