### ISSUE TITLE
Fix requirements.txt to be less restrictive

### ISSUE THREAD

**Issue by ultimatespirit** [hurlenko/mloader#5]
Hi,

I was recently writing an arch PKGBUILD for mloader and ran into some issues with the `requirements.txt`. This is a minor enough change that rather than opening a PR I felt an issue made more sense.

Issue:

Currently mloader's `requirements.txt` restricts to *exact* package versions with `==`. This is most likely not intentional, seeing as how it seems to run fine with newer versions of the required packages. In practice this means on systems with newer versions of the required packages any install from `python setup.py install` will fail at run time (I assume pip to just install multiple package versions).

Proposal:

Change `requirements.txt` to use `>=` or `~=` instead of `==`. I.e. `sed -i.bak 's/==/>=/' requirements.txt` (or `~=` instead of `>=`, should be equivalent here)

P.S. Let me know if you are interested in the PKGBUILD / have any preferences about mloader's being in the Arch User Repository (AUR) or not.

**Comment by hurlenko** [comment]
Hi,

Should be fixed by a7b2d75feb98edf9d60e6f6b5cd63c9c91004116 . As for the PKGBUILD, I'm not an Arch user but I'm glad to help, so if you need anything from my side feel free to write here or open another issue.
