### ISSUE TITLE
Sakamoto Days chapter 123 is mistakenly considered an oneshot

### ISSUE THREAD

**Issue by 10SecondsToWaste** [hurlenko/mloader#56]
**Steps to replicate**

Install the `develop` branch, [change `AUTH_PARAMS`](https://github.com/hurlenko/mloader/issues/36), then run the following:

```shell
$ mloader --format raw --chapter 1017028
```

* Actual name: `Sakamoto Days - 000 (web) [Oneshot] [Unknown]`
* Expected name: Sakamoto Days - c123 (web) [Unknown]`

This chapter's name is "*One shot*". This is probably the cause.

**Environment:**
 - mloader version: 1.1.10@develop
 - Mangaplus URL: https://mangaplus.shueisha.co.jp/viewer/1017028

**Comment by rokibhasansagar** [comment]
https://github.com/hurlenko/mloader/blob/develop/mloader/utils.py needs to be updated to fix this issue 🤔 

@10SecondsToWaste, Replace the `is_oneshot` definition with below code in `utils.py`:

```python3
def is_oneshot(chapter_name: str, chapter_subtitle: str) -> bool:
    chapnum = chapter_name_to_int(chapter_name)
    if chapnum:
        return False
    else:
        for name in (chapter_name, chapter_subtitle):
            name = name.lower()
            if "one" in name and "shot" in name:
                return True
    return False
```

I just tested this changed code and it works.

**Comment by rokibhasansagar** [comment]
Hmm, the PR #57 looks good.
I used `if..else` conditional in my fix, but on second look, that was not necessary.
