### ISSUE TITLE
Fix filenames / archive layout

### ISSUE THREAD

**Issue by ultimatespirit** [hurlenko/mloader#6]
This issue shall be laid out in three parts in order of ease of fixing, with the third part being more of an enhancement / suggestions. It can also serve as a good template for a prospective pull request to reference against.

### Filenames are currently erroneously formatted
The [`format_image_name`](https://github.com/hurlenko/mloader/blob/master/mloader/mloader.py#L39) function currently erroneously formats files with two `.` characters, due to preceding `{ext}` with `.` while defaulting / expecting `ext` to include the `.` of the extension.

Fix: Remove the `.` in the format string or set `ext` to be `ext.lstrip('.')` to allow for `ext = ".png"` and `ext = "png"` to both be valid.

### cbz archive is currently a flat archive
It would be highly preferable for the created cbz archive to be of a *folder* containing the individual pages rather than of the files themselves. I.e. rather than the layout of `manga-chapter.cbz` being `manga-001.png`, `manga-002.png`,... it should be `manga-chapter/manga-001.png`.

Fix: Change [`add_image`](https://github.com/hurlenko/mloader/blob/master/mloader/mloader.py#L83) to use `str(Path(self.path.stem)/self.format_image_name(index)))` for the first argument to `writestr`. Alternatively, `str(self.name.relative_to(self.name.parent).with_suffix('') / self.format_image_name(index))` would work without having to recast `stem` to `Path`. Either way it looks ugly for a one liner.

### Filenames do not conform with established manga archival conventions
This one is the biggest set of changes though mainly deals with the same two functions from above. Currently none of the filenames used by mloader conform to current best practices. Chief among them is that the individual pages do not include their chapter number in their names. Combined with the current issue that the archives are flat (above) this is just asking for files to get clobbered by accident. For best standards refer to [Daiz](https://github.com/Daiz/manga-naming-scheme).

This would mainly require changing `format_image_name` and the initial cbz creation line in `CBZExporter` to include info about chapter number and some extra formatting. The most stringent conforming implementation would have the following layout for chapter 29 of a manga named "Foo" consisting of png pages (for simplicity).

```
Foo - c029 (web) [Viz]/
Foo - c029 (web) [Viz]/Foo - c029 (web) - p001 [Viz].png
...
Foo - c029 (web) [Viz]/Foo - c029 (web) - p022 [Viz].png
```
(If the chapter number exceeds 999 the numbering becomes `d1000` starting at the 1000th chapter)

Fix: It is, of course, personal choice if you wish to fully conform to existing best practices. However, at the very least it would be helpful to modify `format_image_name` to take the chapter number as well (or make a version specifically for `CBZExporter` which already has said info) and format pages as `{self.title} - c{self.chapnum:0>3} - p{self.index:0>3}.{ext}` (assuming the extension issue is fixed by specifying `ext` as `"png"` instead of `".png"`).

**Comment by hurlenko** [comment]
Hi, thanks for your detailed suggestions with possible solutions (really helpful). Will work on this one and #5 on Sunday as I currently don't have much time.

**Comment by hurlenko** [comment]
Hi,

This issue should be fixed in the latest mloader release (1.1.2). If you find any other problems feel free to open another issue.

**Comment by ultimatespirit** [comment]
Thanks! Can confirm everything works with both #6 and #5.

Just a note, while the current page numbers will sort fine, and thus I have no issues with it per se, it currently has a space between the '[Group]' identifier and '.png' for all file names. Additionally it is using just a space as opposed to ` - ` between the chapter prefix and page numbers. They'll sort just fine so feel free to ignore this, but if you wanted to fix that you can change [`format_page_name`](https://github.com/hurlenko/mloader/blob/master/mloader/exporter.py#L105) to instead return `f"{self._chapter_prefix} - {page} {self._chapter_suffix}.{ext.lstrip('.')}"` though I agree it looks much less elegant that way than what you currently are using. (Also the various parts may need a whitespace strip since I didn't check how they're formed for if doing it this way will introduce more whitespace issues).

**Comment by hurlenko** [comment]
Hi!

Thanks for checking, should be fixed in version 1.1.3 🙂

**Comment by ultimatespirit** [comment]
Can confirm, everything looks fine now. Thanks! If I get the chance I'll probably upload the arch-related package stuff I've done for this to the arch user repositories, maybe will help others use your great work :)

**Comment by hurlenko** [comment]
Sounds cool, if you need anything on my end just let me know.
