### ISSUE TITLE
Error when downloading a manga

### ISSUE THREAD

**Issue by Vorffeed** [hurlenko/mloader#61]
I don't know if they have updated the web or what exactly it is because until yesterday the downloads were working without problems.

Here is what the mloader tells me when downloading

![mloader](https://github.com/hurlenko/mloader/assets/10000442/8d656281-f5e8-46a2-afc8-2a39ec43065d)

 - OS: Windows 10 x64
 - Python version: python 3.11.6 x64
 - mloader version: 1.1.11
 - Mangaplus URL: https://mangaplus.shueisha.co.jp/viewer/2010475

**Comment by AkunXdownload** [comment]
I also encountered the same bug

**Comment by Chadoudud** [comment]
same here

**Comment by dousherve** [comment]
Yeah they changed the API. I have the same problem with my own code now nothing works anymore, the API responses seem encoded and I can't find .proto files...

**Comment by Vorffeed** [comment]
> Yeah they changed the API. I have the same problem with my own code now nothing works anymore, the API responses seem encoded and I can't find .proto files...

thank you very much for the solution 😉

**Comment by thiagonl** [comment]
thank you for the fix!

> Yeah they changed the API. I have the same problem with my own code now nothing works anymore, the API responses seem encoded and I can't find .proto files...

thank you for the quick fix!

**Comment by Son1k3** [comment]
Is there any news? The fix doesn't seem to work now.

**Comment by GitWhiv** [comment]
Same bug. is there any fix?

**Comment by Vorffeed** [comment]
> Is there any news? The fix doesn't seem to work now.
The fix is still working perfectly, tested just a few minutes ago.
![Capt](https://github.com/hurlenko/mloader/assets/10000442/fb8d610c-80d9-4603-a0d1-7f681cf0bbbb)
