### ISSUE TITLE
Filename extension saved as PNG instead of JPG

### ISSUE THREAD

**Issue by Zcehtro** [hurlenko/mloader#7]
mloader saves all images when using the -raw parameter as PNG when actually (as far as I've downloaded) they're JPG.

This I can verify when opening any image in irfanview and the program will say that it detected that the image is JPG, and it'll ask if I want to rename the extension.

I imagine that it detects this by looking at the file metadata.

Could you make mloader save the images as JPG?

**Comment by hurlenko** [comment]
Hi @Zcehtro !

Indeed, the correct file extension should be `jpg`. Thanks for letting me know. Fixed in version `1.1.4`
